// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqACeqlCd9Qr_rWYRd4Q5BqStINiR9AKE',
    appId: '1:706195142533:web:c4bf4ed0ea577eff7076ec',
    messagingSenderId: '706195142533',
    projectId: 'topup2p',
    authDomain: 'topup2p.firebaseapp.com',
    databaseURL: 'https://topup2p-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topup2p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAc5oubAXVKc7Kn3r_uT6IMNVJfwPnFsU',
    appId: '1:706195142533:android:f152f1ff24cf8eb07076ec',
    messagingSenderId: '706195142533',
    projectId: 'topup2p',
    databaseURL: 'https://topup2p-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topup2p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZvV6V_fSprE-7e2hAgP5rOt0Tbfgwjw',
    appId: '1:706195142533:ios:da407c67be33264a7076ec',
    messagingSenderId: '706195142533',
    projectId: 'topup2p',
    databaseURL: 'https://topup2p-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topup2p.appspot.com',
    iosClientId: '706195142533-8s87gkgqa3h4kbl0eveij3oglks8b8a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.topup2p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZvV6V_fSprE-7e2hAgP5rOt0Tbfgwjw',
    appId: '1:706195142533:ios:da407c67be33264a7076ec',
    messagingSenderId: '706195142533',
    projectId: 'topup2p',
    databaseURL: 'https://topup2p-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'topup2p.appspot.com',
    iosClientId: '706195142533-8s87gkgqa3h4kbl0eveij3oglks8b8a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.topup2p',
  );
}
